app:
    build:
      context: .
      dockerfile: dockerfile
    container_name: crm-lms-backend_app
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://postgres:root@db:5432/crm-lms-backend?schema=public
      REDIS_URL: redis://redis:6379
      PORT: 3000
    ports:  
      - "4040:3000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    command: >
      sh -c "npx prisma migrate deploy && node dist/main.js"
    networks:
      - crm-lms-backend_network